#server:
#  port: 8888
#
#invoicing-system:
#  database: file
#  database.directory: db
#  database.invoices.file: invoices.txt
#  database.id.file: id.txt
#
#  logging:
#    level:
#      org:
#        springframework:
#          boot: INFO
#      pl:
#        project:
#          invoicing: WARN
#          invoicing.db: DEBUG